name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install WordPress
      run: |
        sudo apt update
        sudo apt install wordpress
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: "/var/www/html"
    - name: Configure WordPress
      run: |
        sed -i "s/database_name='wordpress'/database_name='my_database'/g" wp-config.php
        sed -i "s/database_user='root'/database_user='my_user'/g" wp-config.php
        sed -i "s/database_password=''/database_password='redhat'/g" wp-config.php

